export type ErrorCode =
  | 'INTERNAL_ERROR'
  | 'NEWSLETTER_SUBSCRIBE_FAILED'
  | 'NOT_AUTHENTICATED'
  | 'FOLDER_ALREADY_EXIST'
  | 'FOLDERS_DONT_BELONG_TO_USER'
  | 'SNIPPET_ALREADY_EXIST'
  | 'CANT_DELETE_ROOT_FOLDER'
  | 'USER_ROOT_FOLDER_NOT_FOUND'
  | 'LOGIN_FAILED';
