export const NEWSLETTER_SUBSCRIBE_FAILED_CODE = 'NEWSLETTER_SUBSCRIBE_FAILED';
export const NEWSLETTER_SUBSCRIBE_FAILED_MESSAGE = 'Failed to subscribe to the newsletter.';
export const FOLDER_ALREADY_EXIST_CODE = 'FOLDER_ALREADY_EXIST';
export const FOLDER_ALREADY_EXIST_MESSAGE = (folderName: string) => `A folder named "${folderName}" already exists`;
export const FOLDERS_DONT_BELONG_TO_USER_CODE = 'FOLDERS_DONT_BELONG_TO_USER';
export const FOLDERS_DONT_BELONG_TO_USER_MESSAGE = "One or may folders don't belong to the current user";
export const CANT_DELETE_ROOT_FOLDER_CODE = 'CANT_DELETE_ROOT_FOLDER';
export const CANT_DELETE_ROOT_FOLDER_MESSAGE = 'The root folder cannot be deleted.';
export const SNIPPET_ALREADY_EXIST_CODE = 'SNIPPET_ALREADY_EXIST';
export const SNIPPET_ALREADY_EXIST_MESSAGE = (snippetName: string) => `A snippet named "${snippetName}" already exists`;
export const ROLE_USER_NOT_FOUND = 'Role user not found';
