name: Deploy the Frontend
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version of the frontend to release'
        type: string
        required: true
        default: 'latest'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Production'
    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn 4
        run: |
          corepack enable
          yarn set version 4.3.1

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        env:
          APP_VERSION: $(git rev-parse --short ${{ github.sha }})
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
