name: Sharingan Deploy Code Embed
on:
  workflow_dispatch:
    inputs:
      stage:
        default: Production
        options:
          - Production
          - Development
        description: "Environment to deploy on"
        required: true
  push:
    branches:
      - main
    paths:
      - 'packages/database/prisma/**'
      - 'packages/database/src/**'
      - 'apps/functions/code-embed/src/**'
      - 'apps/functions/code-embed/serverless.ts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.stage }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMBED_STYLE_URL: ${{ secrets.EMBED_STYLE_URL }}
      EMBED_JS_URL: ${{ secrets.EMBED_JS_URL }}
      WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install projects dependencies
        uses: bahmutov/npm-install@v1

      - name: Deploy the application in staging
        working-directory: 'apps/functions/code-embed'
        if: ${{ github.event.inputs.stage == 'Development' }}
        run: |
          yarn setup:layer:remote
          yarn sls deploy --stage dev

      - name: Deploy the application in production
        working-directory: 'apps/functions/code-embed'
        if: ${{ github.event.inputs.stage == 'Production' }}
        run: |
          yarn setup:layer:remote
          yarn sls deploy --stage prod

