name: Infrastructure Plan

on:
  pull_request:
    paths:
      - '_infra/credentials/**/*.tf'
      - '_infra/global/**/*.tf'
      - 'apps/backend/_infra/prod/storage/**/*.tf'
      - 'apps/backend/_infra/prod/compute/**/*.tf'

env:
  TF_API_TOKEN: "${{ secrets.TERRAFORM_API_TOKEN }}"
  TF_CLOUD_ORGANIZATION: ${{ secrets.TERRAFORM_CLOUD_ORGANIZATION }}
  TF_VAR_organization: "\"${{ secrets.TERRAFORM_CLOUD_ORGANIZATION }}\""

jobs:
  plan-credentials:
    runs-on: ubuntu-latest

    outputs:
      infraChanged: ${{ steps.infra-changed.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if infra files changed
        id: infra-changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            _infra/credentials/**/*.tf

      - name: Run terraform plan
        if: ${{ steps.infra-changed.outputs.any_changed == 'true' }}
        uses: ./.github/actions/terraform-plan
        with:
          APP_NAME: 'App Credentials'
          TF_DIRECTORY: '_infra/credentials'
          TF_WORKSPACE: 'snipcode-credentials'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plan-global:
    runs-on: ubuntu-latest

    outputs:
      infraChanged: ${{ steps.infra-changed.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if infra files changed
        id: infra-changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            _infra/global/**/*.tf

      - name: Run terraform plan
        if: ${{ steps.infra-changed.outputs.any_changed == 'true' }}
        uses: ./.github/actions/terraform-plan
        with:
          APP_NAME: 'App Global'
          TF_DIRECTORY: '_infra/global'
          TF_WORKSPACE: 'snipcode-global'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plan-backend-storage:
    runs-on: ubuntu-latest

    outputs:
      infraChanged: ${{ steps.infra-changed.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if infra files changed
        id: infra-changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            apps/backend/_infra/prod/storage/**/*.tf

      - name: Run terraform plan
        if: ${{ steps.infra-changed.outputs.any_changed == 'true' }}
        uses: ./.github/actions/terraform-plan
        with:
          APP_NAME: 'Backend Storage'
          TF_DIRECTORY: 'apps/backend/_infra/prod/storage'
          TF_WORKSPACE: 'snipcode-backend-storage-prod'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plan-backend-compute:
    runs-on: ubuntu-latest

    outputs:
      infraChanged: ${{ steps.infra-changed.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if infra files changed
        id: infra-changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            apps/backend/_infra/prod/compute/**/*.tf

      - name: Run terraform plan
        if: ${{ steps.infra-changed.outputs.any_changed == 'true' }}
        uses: ./.github/actions/terraform-plan
        with:
          APP_NAME: 'Backend Compute'
          TF_DIRECTORY: 'apps/backend/_infra/prod/compute'
          TF_WORKSPACE: 'snipcode-backend-compute-prod'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
