name: Deploy database migration
on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/domain/prisma/migrations/**'

jobs:
  apply-migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Doppler CLI
        run: curl -Ls https://cli.doppler.com/install.sh | sh

      - name: Retrieve and export the database URL
        run: echo "DATABASE_URL=$(doppler secrets get CONNECTION_STRING --plain)" >> $GITHUB_ENV
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_DATABASE_TOKEN }}

      - name: Deploy schema migration to the production database
        run: yarn workspace @snipcode/domain db:deploy
